const actionTypes = {
  UPDATE_USER: "UPDATE_USER",
  UPDATE_JOBS: "UPDATE_JOBS",
  UPDATE_LOADING_STATUS: "UPDATE_LOADING_STATUS",
  JOB_ACCEPT: "JOB_ACCEPT",
  JOB_REJECT: "JOB_REJECT",
  ERROR: "ERROR"
};

export default actionTypes;
